### ISSUE TITLE
Selecting a research question

### ISSUE THREAD

**Issue by blei7** [UBC-MDS/DSCI_522_blei7_georgejjw_coco#2]
Please select one question from below:

1.  Does higher cocoa solids concentration lead to better rating?
2.  Which countries produce better chocolate bar?
3.  Which bean type produce better chocolate bar?

Also, please confirm the question type:

1.  Predictive
2.  Exploratory
3.  Exploratory

**Comment by GeorgeJJW** [comment]
The first question really piqued my interests.
I propose that we rephrase the first question into the following:

"What is the relationship between cocoa percentage (darkness) and expert ratings?"

I believe this question is a exploratory question, rather than a predictive question.
What do you think?

**Comment by blei7** [comment]
Sound good, we will go with it.
